import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientWrapper from "../component/ClientWrapper"; 
import CustomCursor from "../component/CustomCursor";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata = {
  title: "Aman_Portfolio",
  description: "Generated by Aman Nakoti",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClientWrapper>
          <CustomCursor />
          {children}
        </ClientWrapper>
      </body>
    </html>
  );
}
